site_url = "https://allyvenezia.github.io/Ally-Portfolio/index.html"
archive_url = "https://web.archive.org/web/20260911234916/https://allyvenezia.github.io/Ally-Portfolio/index.html"
backlink_urls = [
  "https://irisfisher.github.io/discoveries_in_the_tidepools/index.html",
  "https://second-other-domain.example/page",
]
